-d C:\Workspace\NES\NESTang\Verilator_FormalVerification\workspace\04paritycheck\impl\gwsynthesis\blink_led.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Workspace\NES\NESTang\Verilator_FormalVerification\workspace\04paritycheck\src\paritycheck.cst
-cfg C:\Workspace\NES\NESTang\Verilator_FormalVerification\workspace\04paritycheck\impl\pnr\device.cfg
-sdc C:\Workspace\NES\NESTang\Verilator_FormalVerification\workspace\04paritycheck\src\paritycheck.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
